swapiCache/Controllers/PeopleController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Newtonsoft.Json;
using swapiCache.Data;
using swapiCache.Models;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Drawing;
using System.Runtime.InteropServices;

namespace swapiCache.Controllers
{
    public class PeopleController : Controller
    {
        // GET: PeopleController/id
        public async Task<IActionResult> Index(int id)
        {
            People people = new People();
            try
            {
                if (id == 0)
                    return View("Text", "You must specify an ID");
                else
                {
                    Debug.Print("Looking for id " + id.ToString() + " in database");
                    using (SqlConnection oConecction = new SqlConnection(Connection.connectionLocalStorage))
                    {
                        SqlCommand cmd = new SqlCommand("[peopleById]", oConecction);
                        cmd.CommandType = System.Data.CommandType.StoredProcedure;
                        cmd.Parameters.AddWithValue("@id", id);

                        oConecction.Open();
                        cmd.ExecuteNonQuery();

                        using (SqlDataReader dr = cmd.ExecuteReader())
                        {
                            if (dr.HasRows)
                            {
                                dr.Read();
                                people.name = dr["name"].ToString();
                                people.birth_year = dr["birth_year"].ToString();
                                people.eye_color = dr["eye_color"].ToString();
                                people.gender = dr["gender"].ToString();
                                people.hair_color = dr["hair_color"].ToString();
                                people.height = dr["height"].ToString();
                                people.homeworld = dr["homeworld"].ToString();
                                people.mass = dr["mass"].ToString();
                                people.skin_color = dr["skin_color"].ToString();
                                people.created = dr["created"].ToString();
                                people.edited = dr["edited"].ToString();
                                people.url = dr["url"].ToString();
                            }
                            else
                            {
                                // id isn't in db, querying api
                                string url = "https://swapi.dev/api/people/" + id.ToString();
                                
                                Debug.Print("Loading url for nonchaed id:" + url);
                                using (var httpClient = new HttpClient())
                                {
                                    using (var response = await httpClient.GetAsync(url))
                                    {
                                        
                                        string apiResponse = await response.Content.ReadAsStringAsync();
                                        if (response.StatusCode == System.Net.HttpStatusCode.OK)
                                            people = JsonConvert.DeserializeObject<People>(apiResponse);
                                        else
                                            return View("Text", "Error queriying the people api, id not found");
                                    }
                                }
                            }
                        }
                    }
                }
                if (people is null)
                {
                    return View("Text", "The people Id wasnt found in the api");
                }
                return View("Detail", people);
            }
            catch (Exception ex)
            {
                return View("Text", "Error in people controller: " + ex.Message.ToString());
            }
        }
        // GET: GetPeopleWithLimit/int limit
        public async Task<IActionResult> GetPeopleWithLimit(int limit)
        {
            Peoples peoples = new Peoples();
            bool keepLoading = true;
            string url = "https://swapi.dev/api/people";
            int added = 0;

            try
            {
                while (keepLoading)
                {
                    Debug.Print("Loading url:" + url);
                    using (var httpClient = new HttpClient())
                    {
                        using (var response = await httpClient.GetAsync(url))
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            peoples = JsonConvert.DeserializeObject<Peoples>(apiResponse);

                            foreach (People people in peoples.results)
                            {
                                Debug.Print("Inserting people " + people.name);
                                using (SqlConnection oConecction = new SqlConnection(Connection.connectionLocalStorage))
                                {
                                    SqlCommand cmd = new SqlCommand("[addPeople]", oConecction);
                                    cmd.CommandType = System.Data.CommandType.StoredProcedure;
                                    cmd.Parameters.AddWithValue("@name", people.name);
                                    cmd.Parameters.AddWithValue("@birth_year", people.birth_year);
                                    cmd.Parameters.AddWithValue("@eye_color", people.eye_color);
                                    cmd.Parameters.AddWithValue("@gender", people.gender);
                                    cmd.Parameters.AddWithValue("@hair_color", people.hair_color);
                                    cmd.Parameters.AddWithValue("@height ", people.height);
                                    cmd.Parameters.AddWithValue("@homeworld ", people.homeworld);
                                    cmd.Parameters.AddWithValue("@mass ", people.mass);
                                    cmd.Parameters.AddWithValue("@skin_color ", people.skin_color);
                                    cmd.Parameters.AddWithValue("@created ", people.created);
                                    cmd.Parameters.AddWithValue("@edited ", people.edited);
                                    cmd.Parameters.AddWithValue("@url ", people.url);
                                    oConecction.Open();
                                    cmd.ExecuteNonQuery();
                                    added++;

                                    if (limit != 0)
                                    {
                                        if (added == limit)
                                        {
                                            keepLoading = false;
                                            break;
                                        }
                                    }
                                }
                            }
                            if (peoples.next is null)
                                keepLoading = false;
                            else
                            {
                                url = peoples.next;
                            }
                        }
                    }
                }
                return View("Text", added.ToString() + " peoples were added to the cache");
            }
            catch(Exception ex)
            {
                return View("Text", "Error in GetPeopleWithLimit: " + ex.Message.ToString());
            }
        }
    }
}

swapiCache/Controllers/PlanetController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Newtonsoft.Json;
using swapiCache.Data;
using swapiCache.Models;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Drawing;
using System.Runtime.InteropServices;

namespace swapiCache.Controllers
{
    public class PlanetController : Controller
    {
        // GET: Planet/id
        public async Task<IActionResult> Index(int id)
        {
            Planet planet = new Planet();
            try
            {
                if (id == 0)
                    return View("Text", "You must specify an ID");
                else
                {
                    Debug.Print("Looking for id " + id.ToString() + " in planets database");
                    using (SqlConnection oConecction = new SqlConnection(Connection.connectionLocalStorage))
                    {
                        SqlCommand cmd = new SqlCommand("[planetById]", oConecction);
                        cmd.CommandType = System.Data.CommandType.StoredProcedure;
                        cmd.Parameters.AddWithValue("@id", id);

                        oConecction.Open();
                        cmd.ExecuteNonQuery();

                        using (SqlDataReader dr = cmd.ExecuteReader())
                        {
                            if (dr.HasRows)
                            {
                                dr.Read();
                                planet.climate = dr["climate"].ToString();
                                planet.diameter = dr["diameter"].ToString();
                                planet.gravity = dr["gravity"].ToString();
                                planet.name = dr["name"].ToString();
                                planet.population = dr["population"].ToString();
                                planet.residentsString = dr["residents"].ToString();
                                planet.terrain = dr["terrain"].ToString();
                                planet.url = dr["url"].ToString();
                            }
                            else
                            {
                                // id isn't in db, querying api
                                string url = "https://swapi.dev/api/planet/" + id.ToString();

                                Debug.Print("Loading url for nonchaed planet id:" + url);
                                using (var httpClient = new HttpClient())
                                {
                                    using (var response = await httpClient.GetAsync(url))
                                    {
                                        string apiResponse = await response.Content.ReadAsStringAsync();
                                        if(response.StatusCode== System.Net.HttpStatusCode.OK)
                                            planet = JsonConvert.DeserializeObject<Planet>(apiResponse);
                                        else
                                            return View("Text", "Error querying planet api, id not found");
                                    }
                                }
                            }
                        }
                    }
                }
                if (planet is null)
                {
                    return View("Text", "The planet Id wasnt found in the api");
                }
                return View("Detail", planet);
            }
            catch (Exception ex)
            {
                return View("Text", "Error in planet controller: " + ex.Message.ToString());
            }
        }



        // GET: GetPlanetsWithLimit
        public async Task<IActionResult> GetPlanetsWithLimit(int limit)
        {
            Planets planets = new Planets();
            bool keepLoading = true;
            string url = "https://swapi.dev/api/planets";
            int added = 0;

            try
            {
                while (keepLoading)
                {
                    Debug.Print("Loading url:" + url);
                    using (var httpClient = new HttpClient())
                    {
                        using (var response = await httpClient.GetAsync(url))
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            planets = JsonConvert.DeserializeObject<Planets>(apiResponse);

                            foreach (Planet planet in planets.results)
                            {
                                Debug.Print("Inserting planet " + planet.name);
                                using (SqlConnection oConecction = new SqlConnection(Connection.connectionLocalStorage))
                                {
                                    SqlCommand cmd = new SqlCommand("[addPlanet]", oConecction);
                                    cmd.CommandType = System.Data.CommandType.StoredProcedure;
                                    cmd.Parameters.AddWithValue("@climate", planet.climate);
                                    cmd.Parameters.AddWithValue("@diameter", planet.diameter);
                                    cmd.Parameters.AddWithValue("@gravity", planet.gravity);
                                    cmd.Parameters.AddWithValue("@name", planet.name);
                                    cmd.Parameters.AddWithValue("@population", planet.population);
                                    cmd.Parameters.AddWithValue("@residents", planet.residents.Count().ToString());
                                    cmd.Parameters.AddWithValue("@terrain", planet.terrain);
                                    cmd.Parameters.AddWithValue("@url", planet.url);
                                    oConecction.Open();
                                    cmd.ExecuteNonQuery();
                                    added++;

                                    if (limit != 0)
                                    {
                                        if (added == limit)
                                        {
                                            keepLoading = false;
                                            break;
                                        }
                                    }

                                }
                            }
                            if (planets.next is null)
                                keepLoading = false;
                            else
                            {
                                url = planets.next;
                            }
                        }
                    }
                }
                return View("Text", added.ToString() + " planets were added to the cache");
            }
            catch (Exception ex)
            {
                return View("Text", "Error in GetPlanetsWithLimit controller: " + ex.Message.ToString());
            }
        }
    }
}

swapiCache/Views/Shared/GetPeopleWithLimit.cshtml
@model string

@{
    ViewData["Title"] = "GetPeopleWithLimit";
}

<h1>GetPeopleWithLimit</h1>

<br /><br />
<h1><p>@Model peoples were added to the cache</p></h1>

swapiCache/Views/Shared/Text.cshtml
@model string

@{
    ViewData["Title"] = "swapiCache";
}
<br />
<h1>swapiCache</h1>

<br /><br />
<h2><p>@Model</p></h2>

swapiCache/Views/Shared/View.cshtml
@model IEnumerable<swapiCache.Models.Peoples>

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.count)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.next)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.count)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.next)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

swapiCache/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - swapiCache</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/swapiCache.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">swapiCache</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="People" >People</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Planet" >Planets</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - swapiCache - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>